"""add rating to watched

Revision ID: 72aabc0cdbbf
Revises: 89940ab63080
Create Date: 2026-04-22 15:48:25.231335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72aabc0cdbbf'
down_revision: Union[str, Sequence[str], None] = '89940ab63080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watched', sa.Column('rating', sa.Integer(), nullable=True), schema='movie_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watched', 'rating', schema='movie_app')
    # ### end Alembic commands ###
